#defaultView:ImageGrid
SELECT ?item ?creator ?creatorLabel ?image WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
  ?item wdt:P170 wd:Q18611778.
  OPTIONAL { ?item wdt:P18 ?image. }
}
LIMIT 100
