// Regenerates the "Query overview" and "Link overview" sections of
// usefulQueries.wiki from the templates, so the on-wiki documentation cannot
// drift away from what the script actually ships. Run as part of `npm run
// build` (see assemble.mjs).
//
// Everything between a managed heading and the next top-level `== … ==` heading
// (or the end of the file) is replaced; the rest of the page is left untouched.

import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { pathToFileURL } from "node:url";

export const QUERY_HEADING = "== Query overview ==";
export const LINK_HEADING = "== Link overview ==";

const REPO = "https://github.com/kristbaum/usefulQueries";
const blobUrl = (kind, file) => `${REPO}/blob/main/templates/${kind}/${file}`;
const treeUrl = (kind) => `${REPO}/tree/main/templates/${kind}`;

const AUTOGEN_NOTE =
  "<!-- The tables in this section are generated by scripts/generate-wiki.mjs — " +
  "edit the templates on GitHub, not this text. -->";

/** `{{P|P106}}, {{P|P108}}` */
const propertyLinks = (ids) => ids.map((id) => `{{P|${id}}}`).join(", ");

/** `{{Q|Q42}} or {{Q|Q64}}`, or a note that the value does not matter. */
const valueCell = (ids) =>
  ids ? ids.map((id) => `{{Q|${id}}}`).join(" or ") : "''any value''";

/** Link to the template file on GitHub, labelled with the file name. */
const templateLink = (kind) => (tpl) =>
  `[${blobUrl(kind, tpl.file)} ${tpl.file}]`;

/** The `#defaultView:` line decides how the query service renders the result. */
function defaultView(tpl) {
  const line = tpl.template.find((l) => l.trim().startsWith("#defaultView:"));
  return line ? line.trim().slice("#defaultView:".length) : "Table";
}

const queryLink = templateLink("queries");
const linkLink = templateLink("links");

// One query table per scope, in the order a reader meets them: always-on first,
// then the more specific triggers.
const QUERY_TABLES = [
  {
    scope: "entity",
    heading: "Queries shown on every item",
    intro: "These buttons appear on all items, regardless of their statements.",
    columns: ["Button", "Title", "View", "Example item", "Template"],
    cells: (t) => [
      t.emoji,
      t.title,
      defaultView(t),
      `{{Q|${t.example}}}`,
      queryLink(t),
    ],
  },
  {
    scope: "property",
    heading: "Queries triggered by a property",
    intro:
      "These buttons appear when the item has at least one of the listed " +
      "properties, whatever its value.",
    columns: [
      "Button",
      "Title",
      "Triggering property",
      "View",
      "Example item",
      "Template",
    ],
    cells: (t) => [
      t.emoji,
      t.title,
      propertyLinks(t.propertyId),
      defaultView(t),
      `{{Q|${t.example}}}`,
      queryLink(t),
    ],
  },
  {
    scope: "value",
    heading: "Queries triggered by a property value",
    intro:
      "These buttons appear when the item has the listed property set to one " +
      "of the listed values.",
    columns: [
      "Button",
      "Title",
      "Triggering property",
      "Value",
      "View",
      "Example item",
      "Template",
    ],
    cells: (t) => [
      t.emoji,
      t.title,
      propertyLinks(t.propertyId),
      valueCell(t.valueId),
      defaultView(t),
      `{{Q|${t.example}}}`,
      queryLink(t),
    ],
  },
];

// Links are few enough for a single table; the scope shows up as the property /
// value pair that triggers them.
const LINK_TABLE = {
  columns: [
    "Button",
    "Title",
    "Triggering property",
    "Value",
    "Target URL",
    "Example item",
    "Template",
  ],
  cells: (t) => [
    t.emoji,
    t.title,
    propertyLinks(t.propertyId),
    valueCell(t.valueId),
    `<code>${t.urlTemplate}</code>`,
    `{{Q|${t.example}}}`,
    linkLink(t),
  ],
};

function renderTable(columns, rows, cells) {
  const out = ['{| class="wikitable sortable"'];
  out.push(`! ${columns.join(" !! ")}`);
  for (const tpl of rows) {
    out.push("|-");
    out.push(`| ${cells(tpl).join(" || ")}`);
  }
  out.push("|}");
  return out;
}

/**
 * Render the "Query overview" section, heading included.
 * @param {{file: string}[]} templates - Query templates, each with its file name
 * @returns {string} Wikitext, without a trailing newline
 */
export function renderQuerySection(templates) {
  const out = [
    QUERY_HEADING,
    "",
    AUTOGEN_NOTE,
    "",
    "The following tables list every query template shipped with the script, " +
      "grouped by what makes its button appear. They are generated from the " +
      `[${treeUrl("queries")} template files on GitHub]; the ''Example item'' ` +
      "column names an item the query can be tried out on.",
  ];

  for (const table of QUERY_TABLES) {
    const rows = templates.filter((t) => t.scope === table.scope);
    if (rows.length === 0) continue;
    out.push("", `=== ${table.heading} ===`, "", table.intro, "");
    out.push(...renderTable(table.columns, rows, table.cells));
  }

  return out.join("\n");
}

/**
 * Render the "Link overview" section, heading included.
 * @param {{file: string}[]} templates - Link templates, each with its file name
 * @returns {string} Wikitext, without a trailing newline
 */
export function renderLinkSection(templates) {
  const out = [
    LINK_HEADING,
    "",
    AUTOGEN_NOTE,
    "",
    "These buttons do not run a query; they open an external tool for the " +
      "current item. They are generated from the " +
      `[${treeUrl("links")} link templates on GitHub]; the placeholders in the ` +
      "target URL are filled in with the current item's data.",
  ];

  if (templates.length > 0) {
    out.push("");
    out.push(...renderTable(LINK_TABLE.columns, templates, LINK_TABLE.cells));
  }

  return out.join("\n");
}

/**
 * Replace one generated section in a wiki page. The section runs from its
 * heading up to the next top-level heading, so hand-written sections after it
 * (e.g. "== Comments ==") survive. If the heading is absent the section is
 * appended.
 * @param {string} wikitext - Current page source
 * @param {string} heading - The managed heading, e.g. "== Query overview =="
 * @param {string} section - Replacement section, heading included
 * @returns {string} The updated page source
 */
export function replaceSection(wikitext, heading, section) {
  const start = wikitext.indexOf(heading);
  if (start === -1) {
    return wikitext.replace(/\s*$/, "") + "\n\n" + section + "\n";
  }

  const after = wikitext.slice(start + heading.length);
  const next = after.match(/^==[^=].*==\s*$/m);
  const end =
    next === null ? wikitext.length : start + heading.length + next.index;

  // A section at the very end keeps a single trailing newline, so that
  // regenerating an unchanged page is a no-op.
  const tail = wikitext.slice(end);
  return (
    wikitext.slice(0, start) +
    section +
    (tail.trim() === "" ? "\n" : "\n\n" + tail)
  );
}

/**
 * Read templates from a directory, keeping their file names.
 * @param {string} dir - Directory holding the template JSON files
 */
export async function loadTemplates(dir) {
  let files;
  try {
    files = (await readdir(dir)).filter((f) => f.endsWith(".json")).sort();
  } catch {
    return []; // optional directory (e.g. a build variant without links)
  }
  const templates = [];
  for (const file of files) {
    const data = JSON.parse(await readFile(path.join(dir, file), "utf8"));
    templates.push({ file, ...data });
  }
  return templates;
}

/**
 * Regenerate the generated sections of a wiki page on disk.
 * @param {string} wikiPath - Path to the .wiki file
 * @param {string} queriesDir - Directory holding the query templates
 * @param {string} linksDir - Directory holding the link templates
 * @returns {Promise<"updated"|"unchanged"|"skipped">}
 */
export async function updateWikiPage(wikiPath, queriesDir, linksDir) {
  let wikitext;
  try {
    wikitext = await readFile(wikiPath, "utf8");
  } catch {
    return "skipped"; // no wiki page in this build variant
  }

  const queries = await loadTemplates(queriesDir);
  const links = await loadTemplates(linksDir);

  let updated = replaceSection(
    wikitext,
    QUERY_HEADING,
    renderQuerySection(queries),
  );
  updated = replaceSection(updated, LINK_HEADING, renderLinkSection(links));

  if (updated === wikitext) return "unchanged";

  await writeFile(wikiPath, updated, "utf8");
  return "updated";
}

// Allow a standalone run: `node scripts/generate-wiki.mjs`
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const repoRoot = path.resolve(process.cwd());
  const result = await updateWikiPage(
    path.join(repoRoot, "usefulQueries.wiki"),
    path.join(repoRoot, "templates", "queries"),
    path.join(repoRoot, "templates", "links"),
  );
  console.log(`[generate-wiki] usefulQueries.wiki ${result}`);
}
