// Regenerates the "Query overview" section of usefulQueries.wiki from the
// query templates, so the on-wiki documentation cannot drift away from what the
// script actually ships. Run as part of `npm run build` (see assemble.mjs).
//
// Everything between the heading below and the next top-level `== … ==` heading
// (or the end of the file) is replaced; the rest of the page is left untouched.

import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { pathToFileURL } from "node:url";

export const SECTION_HEADING = "== Query overview ==";

const REPO = "https://github.com/kristbaum/usefulQueries";
const BLOB = `${REPO}/blob/main/templates/queries`;
const TREE = `${REPO}/tree/main/templates/queries`;

const AUTOGEN_NOTE =
  "<!-- The tables in this section are generated by scripts/generate-wiki.mjs — " +
  "edit the templates on GitHub, not this text. -->";

const INTRO =
  "The following tables list every query template shipped with the script, " +
  "grouped by what makes its button appear. They are generated from the " +
  `[${TREE} template files on GitHub]; the ''Example item'' column names an ` +
  "item the query can be tried out on.";

/** `{{P|P106}}, {{P|P108}}` */
const propertyLinks = (ids) => ids.map((id) => `{{P|${id}}}`).join(", ");

/** `{{Q|Q42}} or {{Q|Q64}}` */
const valueLinks = (ids) => ids.map((id) => `{{Q|${id}}}`).join(" or ");

/** Link to the template file on GitHub, labelled with the file name. */
const templateLink = (tpl) => `[${BLOB}/${tpl.file} ${tpl.file}]`;

/** The `#defaultView:` line decides how the query service renders the result. */
function defaultView(tpl) {
  const line = tpl.template.find((l) => l.trim().startsWith("#defaultView:"));
  return line ? line.trim().slice("#defaultView:".length) : "Table";
}

// One table per scope, in the order a reader meets them: always-on first, then
// the more specific triggers.
const SECTIONS = [
  {
    scope: "entity",
    heading: "Queries shown on every item",
    intro: "These buttons appear on all items, regardless of their statements.",
    columns: ["Button", "Title", "View", "Example item", "Template"],
    cells: (t) => [t.emoji, t.title, defaultView(t), `{{Q|${t.example}}}`, templateLink(t)],
  },
  {
    scope: "property",
    heading: "Queries triggered by a property",
    intro:
      "These buttons appear when the item has at least one of the listed " +
      "properties, whatever its value.",
    columns: [
      "Button",
      "Title",
      "Triggering property",
      "View",
      "Example item",
      "Template",
    ],
    cells: (t) => [
      t.emoji,
      t.title,
      propertyLinks(t.propertyId),
      defaultView(t),
      `{{Q|${t.example}}}`,
      templateLink(t),
    ],
  },
  {
    scope: "value",
    heading: "Queries triggered by a property value",
    intro:
      "These buttons appear when the item has the listed property set to one " +
      "of the listed values.",
    columns: [
      "Button",
      "Title",
      "Triggering property",
      "Value",
      "View",
      "Example item",
      "Template",
    ],
    cells: (t) => [
      t.emoji,
      t.title,
      propertyLinks(t.propertyId),
      t.valueId ? valueLinks(t.valueId) : "''any value''",
      defaultView(t),
      `{{Q|${t.example}}}`,
      templateLink(t),
    ],
  },
];

/**
 * Render the whole "Query overview" section, heading included.
 * @param {{file: string}[]} templates - Query templates, each with its file name
 * @returns {string} Wikitext, without a trailing newline
 */
export function renderSection(templates) {
  const out = [SECTION_HEADING, "", AUTOGEN_NOTE, "", INTRO];

  for (const section of SECTIONS) {
    const rows = templates.filter((t) => t.scope === section.scope);
    if (rows.length === 0) continue;

    out.push("", `=== ${section.heading} ===`, "", section.intro, "");
    out.push('{| class="wikitable sortable"');
    out.push(`! ${section.columns.join(" !! ")}`);
    for (const tpl of rows) {
      out.push("|-");
      out.push(`| ${section.cells(tpl).join(" || ")}`);
    }
    out.push("|}");
  }

  return out.join("\n");
}

/**
 * Replace the generated section in a wiki page. The section runs from
 * SECTION_HEADING up to the next top-level heading, so hand-written sections
 * after it (e.g. "== Comments ==") survive. If the heading is absent the
 * section is appended.
 * @param {string} wikitext - Current page source
 * @param {string} section - Replacement section from renderSection()
 * @returns {string} The updated page source
 */
export function replaceSection(wikitext, section) {
  const start = wikitext.indexOf(SECTION_HEADING);
  if (start === -1) {
    const separator = wikitext.endsWith("\n") ? "\n" : "\n\n";
    return wikitext + separator + section + "\n";
  }

  const after = wikitext.slice(start + SECTION_HEADING.length);
  const next = after.match(/^==[^=].*==\s*$/m);
  const end =
    next === undefined || next === null
      ? wikitext.length
      : start + SECTION_HEADING.length + next.index;

  return wikitext.slice(0, start) + section + "\n\n" + wikitext.slice(end);
}

/**
 * Read the query templates from a directory, keeping their file names.
 * @param {string} dir - Directory holding the query template JSON files
 */
export async function loadQueryTemplates(dir) {
  const files = (await readdir(dir)).filter((f) => f.endsWith(".json")).sort();
  const templates = [];
  for (const file of files) {
    const data = JSON.parse(await readFile(path.join(dir, file), "utf8"));
    templates.push({ file, ...data });
  }
  return templates;
}

/**
 * Regenerate the query overview in a wiki page on disk.
 * @param {string} wikiPath - Path to the .wiki file
 * @param {string} queriesDir - Directory holding the query templates
 * @returns {Promise<"updated"|"unchanged"|"skipped">}
 */
export async function updateWikiPage(wikiPath, queriesDir) {
  let wikitext;
  try {
    wikitext = await readFile(wikiPath, "utf8");
  } catch {
    return "skipped"; // no wiki page in this build variant
  }

  const templates = await loadQueryTemplates(queriesDir);
  const updated = replaceSection(wikitext, renderSection(templates));
  if (updated === wikitext) return "unchanged";

  await writeFile(wikiPath, updated, "utf8");
  return "updated";
}

// Allow a standalone run: `node scripts/generate-wiki.mjs`
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const repoRoot = path.resolve(process.cwd());
  const result = await updateWikiPage(
    path.join(repoRoot, "usefulQueries.wiki"),
    path.join(repoRoot, "templates", "queries"),
  );
  console.log(`[generate-wiki] usefulQueries.wiki ${result}`);
}
